name: Fly Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-group # ensure only one deploy action runs at a time
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
      - name: Deploy App
        run: flyctl console --dockerfile Dockerfile.builder -C "/srv/deploy.sh" --env "FLY_API_TOKEN=$FLY_API_TOKEN"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WEB_DEPLOY_TOKEN }}
