name: Fly Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-group # ensure only one deploy action runs at a time
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
      - name: Deploy App
        run: flyctl deploy --remote-only --build-secret "GITHUB_TOKEN=$GITHUB_TOKEN" --build-secret "HOOF_AUTH_TOKEN=$HOOF_AUTH_TOKEN"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WEB_DEPLOY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOOF_AUTH_TOKEN: ${{ secrets.HOOF_AUTH_TOKEN }}
